name: Build and deploy .NET Core application to Web App WebApi20240307182110
on:
  push:
    branches:
    - master

jobs:
  call-reusable-workflow:
    uses: mpreddy25/GitHubActions/.github/workflows/workflow-template-webapi-functions-push.yml@master
    with:
        solution_path: GitHubActions
        api_project_filename: WebApi.csproj
        api_project_folder_path: WebApi
        aure_webapp_name: WebApi20240307182110
        functions_project_filename: FunctionAppCICD.csproj
        functions_project_folder_path: FunctionAppCICD
        aure_functionapp_name: FunctionAppCICD20240307173031
    secrets:
        AZURE_WEB_APPS_PUBLISH_PROFILE_TOKEN: ${{ secrets.WebApi20240307182110_DFAE }}
        AZURE_FUNCTION_APPS_PUBLISH_PROFILE_TOKEN: ${{ secrets.FunctionAppCICD20240307173031_EF35 }}