name: Build and deploy .NET Core application to Web App WebApi20240307182110
on:
  push:
    branches:
    - master

jobs:
  call-reusable-workflow:
    uses: mpreddy25/GitHubActions/.github/workflows/workflow-template-webapi-functions-push.yml@master
    secrets:
        AZURE_WEB_APPS_PUBLISH_PROFILE_TOKEN: ${{ secrets.WebApi20240307182110_DFAE }}
        AZURE_FUNCTION_APPS_PUBLISH_PROFILE_TOKEN: ${{ secrets.FunctionAppCICD20240307173031_EF35 }}