name: Build and deploy .NET Core application to Web App WebApi20240307182110
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: WebApi20240307182110
  AZURE_WEBAPP_PACKAGE_PATH: WebApi\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WEBAPI_DIRECTORY: WebApi
  AZURE_FUNCTIONAPP_NAME: FunctionAppCICD20240307173031
  AZURE_FUNCTIONAPP_PACKAGE_PATH: FunctionAppCICD\published
  FUNCTION_APP_DIRECTORY: FunctionAppCICD
  DOTNET_CORE_VERSION_INPROC: 8.0.x
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WEBAPI_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WEBAPI_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WEBAPI_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WEBAPI_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Restore
      run: dotnet restore "${{ env.FUNCTION_APP_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.FUNCTION_APP_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.FUNCTION_APP_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy-function-app:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.FunctionAppCICD20240307173031_EF35 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy-webapp:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.WebApi20240307182110_DFAE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}