name: Build and deploy .NET Core application to Web App WebApi20240307182110
on:
  push:
    branches:
    - master

jobs:
  call-reusable-workflow:
    uses: mpreddy25/GitHubActions/.github/workflows/workflow-template-webapi-push.yml@master
    with:
        solution_path: GitHubActions
        api_project_filename: WebApi.csproj
        api_project_folder_path: WebApi
        aure_webapp_name: 'webapicicd'
        aure_webapp_slot_name: 'staging'
    secrets:
        AZURE_WEB_APPS_PUBLISH_PROFILE_TOKEN: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  swap-webapp-slots:
        needs: call-reusable-workflow
        runs-on: windows-latest
        if: github.event_name == 'workflow_dispatch'

        steps:
        - name: Swap Slots
          uses: azure/webapps-swap@v1
          with:
            app-name: 'webapicicd'
            resource-group: 'mpreddytesting'
            slot1: 'staging'
            slot2: 'production'
            publish-profile: ${{ secrets.AZURE_WEB_APPS_PUBLISH_PROFILE_TOKEN }}
